from eudplib import *

from ...utils import EPDConstString
from . import getWriter

@EUDFunc
def SCMDWriteUnit_var(unit):
    if EUDIf()(unit >= 233):
        getWriter().write_decimal(unit)
    if EUDElseIf()(unit == 228):
        getWriter().write_decimal(unit)
    if EUDElse()():
        getWriter().write_strepd(SCMDDefaultUnitArray[unit])
    EUDEndIf()

def SCMDWriteUnit(unit):
    from ...core.appmanager import getAppManager
    if IsEUDVariable(unit):
        SCMDWriteUnit_var(unit)
    else:
        getWriter().write_f(SCMDDefaultUnits[unit])

SCMDDefaultUnits = [
    "\"Terran Marine\"",
    "\"Terran Ghost\"",
    "\"Terran Vulture\"",
    "\"Terran Goliath\"",
    "\"Goliath Turret\"",
    "\"Terran Siege Tank (Tank Mode)\"",
    "\"Tank Turret type   1\"",
    "\"Terran SCV\"",
    "\"Terran Wraith\"",
    "\"Terran Science Vessel\"",
    "\"Gui Montag (Firebat)\"",
    "\"Terran Dropship\"",
    "\"Terran Battlecruiser\"",
    "\"Vulture Spider Mine\"",
    "\"Nuclear Missile\"",
    "\"Terran Civilian\"",
    "\"Sarah Kerrigan (Ghost)\"",
    "\"Alan Schezar (Goliath)\"",
    "\"Alan Turret\"",
    "\"Jim Raynor (Vulture)\"",
    "\"Jim Raynor (Marine)\"",
    "\"Tom Kazansky (Wraith)\"",
    "\"Magellan (Science Vessel)\"",
    "\"Edmund Duke (Siege Tank)\"",
    "\"Duke Turret type   1\"",
    "\"Edmund Duke (Siege Mode)\"",
    "\"Duke Turret type   2\"",
    "\"Arcturus Mengsk (Battlecruiser)\"",
    "\"Hyperion (Battlecruiser)\"",
    "\"Norad II (Battlecruiser)\"",
    "\"Terran Siege Tank (Siege Mode)\"",
    "\"Tank Turret type   2\"",
    "\"Terran Firebat\"",
    "\"Scanner Sweep\"",
    "\"Terran Medic\"",
    "\"Zerg Larva\"",
    "\"Zerg Egg\"",
    "\"Zerg Zergling\"",
    "\"Zerg Hydralisk\"",
    "\"Zerg Ultralisk\"",
    "\"Zerg Broodling\"",
    "\"Zerg Drone\"",
    "\"Zerg Overlord\"",
    "\"Zerg Mutalisk\"",
    "\"Zerg Guardian\"",
    "\"Zerg Queen\"",
    "\"Zerg Defiler\"",
    "\"Zerg Scourge\"",
    "\"Torrasque (Ultralisk)\"",
    "\"Matriarch (Queen)\"",
    "\"Infested Terran\"",
    "\"Infested Kerrigan (Infested Terran)\"",
    "\"Unclean One (Defiler)\"",
    "\"Hunter Killer (Hydralisk)\"",
    "\"Devouring One (Zergling)\"",
    "\"Kukulza (Mutalisk)\"",
    "\"Kukulza (Guardian)\"",
    "\"Yggdrasill (Overlord)\"",
    "\"Terran Valkyrie\"",
    "\"Cocoon\"",
    "\"Protoss Corsair\"",
    "\"Protoss Dark Templar\"",
    "\"Zerg Devourer\"",
    "\"Protoss Dark Archon\"",
    "\"Protoss Probe\"",
    "\"Protoss Zealot\"",
    "\"Protoss Dragoon\"",
    "\"Protoss High Templar\"",
    "\"Protoss Archon\"",
    "\"Protoss Shuttle\"",
    "\"Protoss Scout\"",
    "\"Protoss Arbiter\"",
    "\"Protoss Carrier\"",
    "\"Protoss Interceptor\"",
    "\"Dark Templar (Hero)\"",
    "\"Zeratul (Dark Templar)\"",
    "\"Tassadar/Zeratul (Archon)\"",
    "\"Fenix (Zealot)\"",
    "\"Fenix (Dragoon)\"",
    "\"Tassadar (Templar)\"",
    "\"Mojo (Scout)\"",
    "\"Warbringer (Reaver)\"",
    "\"Gantrithor (Carrier)\"",
    "\"Protoss Reaver\"",
    "\"Protoss Observer\"",
    "\"Protoss Scarab\"",
    "\"Danimoth (Arbiter)\"",
    "\"Aldaris (Templar)\"",
    "\"Artanis (Scout)\"",
    "\"Rhynadon (Badlands)\"",
    "\"Bengalaas (Jungle)\"",
    "\"Unused type   1\"",
    "\"Unused type   2\"",
    "\"Scantid (Desert)\"",
    "\"Kakaru (Twilight)\"",
    "\"Ragnasaur (Ash World)\"",
    "\"Ursadon (Ice World)\"",
    "\"Zerg Lurker Egg\"",
    "\"Raszagal (Dark Templar)\"",
    "\"Samir Duran (Ghost)\"",
    "\"Alexei Stukov (Ghost)\"",
    "\"Map Revealer\"",
    "\"Gerard DuGalle (Ghost)\"",
    "\"Zerg Lurker\"",
    "\"Infested Duran\"",
    "\"Disruption Field\"",
    "\"Terran Command Center\"",
    "\"Terran Comsat Station\"",
    "\"Terran Nuclear Silo\"",
    "\"Terran Supply Depot\"",
    "\"Terran Refinery\"",
    "\"Terran Barracks\"",
    "\"Terran Academy\"",
    "\"Terran Factory\"",
    "\"Terran Starport\"",
    "\"Terran Control Tower\"",
    "\"Terran Science Facility\"",
    "\"Terran Covert Ops\"",
    "\"Terran Physics Lab\"",
    "\"Unused Terran Bldg type   1\"",
    "\"Terran Machine Shop\"",
    "\"Unused Terran Bldg type   2\"",
    "\"Terran Engineering Bay\"",
    "\"Terran Armory\"",
    "\"Terran Missile Turret\"",
    "\"Terran Bunker\"",
    "\"Norad II (Crashed Battlecruiser)\"",
    "\"Ion Cannon\"",
    "\"Uraj Crystal\"",
    "\"Khalis Crystal\"",
    "\"Infested Command Center\"",
    "\"Zerg Hatchery\"",
    "\"Zerg Lair\"",
    "\"Zerg Hive\"",
    "\"Zerg Nydus Canal\"",
    "\"Zerg Hydralisk Den\"",
    "\"Zerg Defiler Mound\"",
    "\"Zerg Greater Spire\"",
    "\"Zerg Queen's Nest\"",
    "\"Zerg Evolution Chamber\"",
    "\"Zerg Ultralisk Cavern\"",
    "\"Zerg Spire\"",
    "\"Zerg Spawning Pool\"",
    "\"Zerg Creep Colony\"",
    "\"Zerg Spore Colony\"",
    "\"Unused Zerg Bldg\"",
    "\"Zerg Sunken Colony\"",
    "\"Zerg Overmind (With Shell)\"",
    "\"Zerg Overmind\"",
    "\"Zerg Extractor\"",
    "\"Mature Crysalis\"",
    "\"Zerg Cerebrate\"",
    "\"Zerg Cerebrate Daggoth\"",
    "\"Unused Zerg Bldg 5\"",
    "\"Protoss Nexus\"",
    "\"Protoss Robotics Facility\"",
    "\"Protoss Pylon\"",
    "\"Protoss Assimilator\"",
    "\"Protoss Unused type   1\"",
    "\"Protoss Observatory\"",
    "\"Protoss Gateway\"",
    "\"Protoss Unused type   2\"",
    "\"Protoss Photon Cannon\"",
    "\"Protoss Citadel of Adun\"",
    "\"Protoss Cybernetics Core\"",
    "\"Protoss Templar Archives\"",
    "\"Protoss Forge\"",
    "\"Protoss Stargate\"",
    "\"Stasis Cell/Prison\"",
    "\"Protoss Fleet Beacon\"",
    "\"Protoss Arbiter Tribunal\"",
    "\"Protoss Robotics Support Bay\"",
    "\"Protoss Shield Battery\"",
    "\"Khaydarin Crystal Formation\"",
    "\"Protoss Temple\"",
    "\"Xel'Naga Temple\"",
    "\"Mineral Field (Type 1)\"",
    "\"Mineral Field (Type 2)\"",
    "\"Mineral Field (Type 3)\"",
    "\"Cave\"",
    "\"Cave-in\"",
    "\"Cantina\"",
    "\"Mining Platform\"",
    "\"Independent Command Center\"",
    "\"Independent Starport\"",
    "\"Jump Gate\"",
    "\"Ruins\"",
    "\"Kyadarin Crystal Formation\"",
    "\"Vespene Geyser\"",
    "\"Warp Gate\"",
    "\"Psi Disrupter\"",
    "\"Zerg Marker\"",
    "\"Terran Marker\"",
    "\"Protoss Marker\"",
    "\"Zerg Beacon\"",
    "\"Terran Beacon\"",
    "\"Protoss Beacon\"",
    "\"Zerg Flag Beacon\"",
    "\"Terran Flag Beacon\"",
    "\"Protoss Flag Beacon\"",
    "\"Power Generator\"",
    "\"Overmind Cocoon\"",
    "\"Dark Swarm\"",
    "\"Floor Missile Trap\"",
    "\"Floor Hatch (UNUSED)\"",
    "\"Left Upper Level Door\"",
    "\"Right Upper Level Door\"",
    "\"Left Pit Door\"",
    "\"Right Pit Door\"",
    "\"Floor Gun Trap\"",
    "\"Left Wall Missile Trap\"",
    "\"Left Wall Flame Trap\"",
    "\"Right Wall Missile Trap\"",
    "\"Right Wall Flame Trap\"",
    "\"Start Location\"",
    "\"Flag\"",
    "\"Young Chrysalis\"",
    "\"Psi Emitter\"",
    "\"Data Disc\"",
    "\"Khaydarin Crystal\"",
    "\"Mineral Chunk (Type 1)\"",
    "\"Mineral Chunk (Type 2)\"",
    "\"Vespene Orb (Protoss Type 1)\"",
    "\"Vespene Orb (Protoss Type 2)\"",
    "\"Vespene Sac (Zerg Type 1)\"",
    "\"Vespene Sac (Zerg Type 2)\"",
    "\"Vespene Tank (Terran Type 1)\"",
    "\"Vespene Tank (Terran Type 2)\"",
    "\"N/A\"", # 228
    "\"Any unit\"",
    "\"Men\"",
    "\"Buildings\"",
    "\"Factories\"",
]
SCMDDefaultUnitArray = EUDArray(list(map(EPDConstString, SCMDDefaultUnits)))
